#!/bin/sh
PASS=true

# format all files
go fmt ./...

# vet all files
go vet ./...
if [[ $? != 0 ]]; then
  exit 1
fi

# run all tests
go test ./...
if [[ $? == 1 ]]; then
  exit 1
fi

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
for FILE in $STAGED_GO_FILES
do
  # lint any changed files
  golint "-set_exit_status" $FILE
  if [[ $? == 1 ]]; then
    PASS=false
  fi
done

if ! $PASS; then
  printf "Commit Failed\n"
  exit 1
fi

exit 0
